"""
Utility functions for IssuePilot
"""

import json
import re
from typing import Any, Dict, List

from .schemas import AnalysisResult


def validate_repo_format(repo: str) -> bool:
    """
    Validate repository format (owner/repo)

    Args:
        repo: Repository string to validate

    Returns:
        True if valid, False otherwise
    """
    pattern = r"^[\w.-]+/[\w.-]+$"
    return bool(re.match(pattern, repo))


def parse_repo(repo: str) -> tuple:
    """
    Parse repository string into owner and repo name

    Args:
        repo: Repository string in format 'owner/repo'

    Returns:
        Tuple of (owner, repo_name)
    """
    parts = repo.split("/")
    if len(parts) != 2:
        raise ValueError(f"Invalid repo format: {repo}")
    return parts[0], parts[1]


def truncate_text(text: str, max_length: int = 4000) -> str:
    """
    Truncate text to a maximum length while preserving word boundaries

    Args:
        text: Text to truncate
        max_length: Maximum character length

    Returns:
        Truncated text
    """
    if len(text) <= max_length:
        return text

    truncated = text[:max_length]
    last_space = truncated.rfind(" ")
    if last_space > max_length * 0.8:
        truncated = truncated[:last_space]

    return truncated + "..."


def clean_json_response(response: str) -> Dict[str, Any]:
    """
    Clean and parse JSON from AI response

    Args:
        response: Raw response string from AI

    Returns:
        Parsed JSON dictionary
    """
    # Try to extract JSON from markdown code blocks
    json_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", response)
    if json_match:
        response = json_match.group(1)

    # Clean up common issues
    response = response.strip()

    try:
        return json.loads(response)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse AI response as JSON: {e}")


def generate_markdown_export(
    analysis: AnalysisResult, repo: str = "", issue_number: int = 0
) -> str:
    """
    Generate markdown export from analysis result

    Args:
        analysis: Analysis result to export
        repo: Repository name (optional)
        issue_number: Issue number (optional)

    Returns:
        Formatted markdown string
    """
    md_lines = ["# 🔍 Issue Analysis Report", ""]

    if repo and issue_number:
        md_lines.extend(
            [f"**Repository:** `{repo}`", f"**Issue:** #{issue_number}", ""]
        )

    md_lines.extend(
        [
            "---",
            "",
            "## 📋 Summary",
            "",
            analysis.summary,
            "",
            "---",
            "",
            "## 🔬 Root Cause Analysis",
            "",
            analysis.root_cause,
            "",
            "---",
            "",
            "## 🛠️ Solution Steps",
            "",
        ]
    )

    for i, step in enumerate(analysis.solution_steps, 1):
        md_lines.append(f"{i}. {step}")

    md_lines.extend(["", "---", "", "## ✅ Developer Checklist", ""])

    for item in analysis.checklist:
        md_lines.append(f"- [ ] {item}")

    md_lines.extend(
        [
            "",
            "---",
            "",
            "## 🏷️ Suggested Labels",
            "",
            ", ".join([f"`{label}`" for label in analysis.labels]),
            "",
        ]
    )

    if analysis.similar_issues:
        md_lines.extend(["---", "", "## 🔗 Similar Issues", ""])
        for issue in analysis.similar_issues:
            md_lines.append(
                f"- [{issue.title}]({issue.url}) (Similarity: {issue.similarity:.0%})"
            )
        md_lines.append("")

    md_lines.extend(
        [
            "---",
            "",
            "*Generated by [IssuePilot](https://github.com/Scarage1/IssuePilot) 🚀*",
        ]
    )

    return "\n".join(md_lines)


def extract_code_blocks(text: str) -> List[Dict[str, str]]:
    """
    Extract code blocks from issue body

    Args:
        text: Text containing code blocks

    Returns:
        List of dicts with 'language' and 'code' keys
    """
    pattern = r"```(\w*)\n([\s\S]*?)```"
    matches = re.findall(pattern, text)

    return [
        {"language": lang or "text", "code": code.strip()} for lang, code in matches
    ]


def sanitize_input(text: str) -> str:
    """
    Sanitize user input to prevent injection attacks

    Args:
        text: Text to sanitize

    Returns:
        Sanitized text
    """
    if not text:
        return ""

    # Remove null bytes
    text = text.replace("\x00", "")

    # Limit length
    max_length = 50000
    if len(text) > max_length:
        text = text[:max_length]

    return text


def generate_html_export(
    analysis: AnalysisResult, repo: str = "", issue_number: int = 0
) -> str:
    """
    Generate HTML export from analysis result

    Args:
        analysis: Analysis result to export
        repo: Repository name (optional)
        issue_number: Issue number (optional)

    Returns:
        Formatted HTML string
    """

    # Escape HTML entities
    def escape_html(text: str) -> str:
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )

    title = "Issue Analysis Report"
    if repo and issue_number:
        title = f"Analysis: {repo} #{issue_number}"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escape_html(title)}</title>
    <style>
        :root {{
            --primary: #2563eb;
            --primary-light: #dbeafe;
            --success: #22c55e;
            --success-light: #dcfce7;
            --warning: #eab308;
            --warning-light: #fef9c3;
            --purple: #9333ea;
            --purple-light: #f3e8ff;
            --gray-100: #f3f4f6;
            --gray-200: #e5e7eb;
            --gray-600: #4b5563;
            --gray-800: #1f2937;
        }}

        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: var(--gray-800);
            background: var(--gray-100);
            padding: 2rem;
        }}

        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }}

        .header {{
            background: linear-gradient(135deg, var(--primary), #1d4ed8);
            color: white;
            padding: 2rem;
        }}

        .header h1 {{
            font-size: 1.75rem;
            margin-bottom: 0.5rem;
        }}

        .header .meta {{
            opacity: 0.9;
            font-size: 0.875rem;
        }}

        .content {{
            padding: 2rem;
        }}

        .section {{
            margin-bottom: 2rem;
        }}

        .section-header {{
            display: flex;
            align-items: center;
            gap: 0.5rem;
            margin-bottom: 1rem;
        }}

        .section-header h2 {{
            font-size: 1.25rem;
            color: var(--gray-800);
        }}

        .icon {{
            width: 24px;
            height: 24px;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 6px;
            font-size: 0.875rem;
        }}

        .icon-blue {{ background: var(--primary-light); color: var(--primary); }}
        .icon-yellow {{ background: var(--warning-light); color: var(--warning); }}
        .icon-green {{ background: var(--success-light); color: var(--success); }}
        .icon-purple {{ background: var(--purple-light); color: var(--purple); }}

        .card {{
            background: var(--gray-100);
            border-radius: 8px;
            padding: 1rem;
        }}

        .steps {{
            counter-reset: step;
        }}

        .step {{
            display: flex;
            gap: 1rem;
            margin-bottom: 0.75rem;
        }}

        .step-number {{
            width: 24px;
            height: 24px;
            background: var(--success);
            color: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 0.75rem;
            font-weight: 600;
            flex-shrink: 0;
        }}

        .checklist-item {{
            display: flex;
            align-items: flex-start;
            gap: 0.75rem;
            margin-bottom: 0.5rem;
        }}

        .checkbox {{
            width: 18px;
            height: 18px;
            border: 2px solid var(--gray-200);
            border-radius: 4px;
            flex-shrink: 0;
            margin-top: 2px;
        }}

        .labels {{
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
        }}

        .label {{
            background: var(--primary-light);
            color: var(--primary);
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.875rem;
            font-weight: 500;
        }}

        .similar-issue {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0.75rem;
            background: white;
            border: 1px solid var(--gray-200);
            border-radius: 8px;
            margin-bottom: 0.5rem;
        }}

        .similar-issue a {{
            color: var(--primary);
            text-decoration: none;
        }}

        .similar-issue a:hover {{
            text-decoration: underline;
        }}

        .similarity {{
            background: var(--gray-100);
            padding: 0.25rem 0.5rem;
            border-radius: 4px;
            font-size: 0.75rem;
            color: var(--gray-600);
        }}

        .footer {{
            text-align: center;
            padding: 1.5rem;
            background: var(--gray-100);
            color: var(--gray-600);
            font-size: 0.875rem;
        }}

        .footer a {{
            color: var(--primary);
            text-decoration: none;
        }}

        @media print {{
            body {{
                background: white;
                padding: 0;
            }}
            .container {{
                box-shadow: none;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔍 Issue Analysis Report</h1>
"""

    if repo and issue_number:
        html += f"""            <div class="meta">
                Repository: <strong>{escape_html(repo)}</strong> &bull; Issue: <strong>#{issue_number}</strong>
            </div>
"""

    html += f"""        </div>

        <div class="content">
            <div class="section">
                <div class="section-header">
                    <span class="icon icon-blue">📋</span>
                    <h2>Summary</h2>
                </div>
                <div class="card">
                    <p>{escape_html(analysis.summary)}</p>
                </div>
            </div>

            <div class="section">
                <div class="section-header">
                    <span class="icon icon-yellow">🔬</span>
                    <h2>Root Cause Analysis</h2>
                </div>
                <div class="card">
                    <p>{escape_html(analysis.root_cause)}</p>
                </div>
            </div>

            <div class="section">
                <div class="section-header">
                    <span class="icon icon-green">🛠️</span>
                    <h2>Solution Steps</h2>
                </div>
                <div class="steps">
"""

    for i, step in enumerate(analysis.solution_steps, 1):
        html += f"""                    <div class="step">
                        <span class="step-number">{i}</span>
                        <span>{escape_html(step)}</span>
                    </div>
"""

    html += """                </div>
            </div>

            <div class="section">
                <div class="section-header">
                    <span class="icon icon-purple">✅</span>
                    <h2>Developer Checklist</h2>
                </div>
                <div class="card">
"""

    for item in analysis.checklist:
        html += f"""                    <div class="checklist-item">
                        <div class="checkbox"></div>
                        <span>{escape_html(item)}</span>
                    </div>
"""

    html += """                </div>
            </div>

            <div class="section">
                <div class="section-header">
                    <span class="icon icon-blue">🏷️</span>
                    <h2>Suggested Labels</h2>
                </div>
                <div class="labels">
"""

    for label in analysis.labels:
        html += f"""                    <span class="label">{escape_html(label)}</span>
"""

    html += """                </div>
            </div>
"""

    if analysis.similar_issues:
        html += """            <div class="section">
                <div class="section-header">
                    <span class="icon icon-yellow">🔗</span>
                    <h2>Similar Issues</h2>
                </div>
"""
        for issue in analysis.similar_issues:
            html += f"""                <div class="similar-issue">
                    <a href="{escape_html(issue.url)}" target="_blank">{escape_html(issue.title)}</a>
                    <span class="similarity">{issue.similarity:.0%} match</span>
                </div>
"""
        html += """            </div>
"""

    html += """        </div>

        <div class="footer">
            Generated by <a href="https://github.com/Scarage1/IssuePilot" target="_blank">IssuePilot</a> 🚀
        </div>
    </div>
</body>
</html>"""

    return html
